ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "peakRating" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "rankedGames" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "rankedWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "rankedLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "rankedDraws" INTEGER NOT NULL DEFAULT 0;
