name: AnagramArena
options:
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.benh.anagramarena
packages: {}
targets:
  AnagramArena:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    info:
      path: Resources/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        SWIFT_VERSION: 5.10
    scheme:
      testTargets:
        - AnagramArenaTests
  AnagramArenaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: AnagramArena